### ISSUE TITLE
关于Postcss 使用函数 处理1px 背景图片问题

### ISSUE THREAD

**Issue by facebook201** [facebook201/Company-learnList#2]
首先我们要安装几个postcss 插件 
```JavaScript
var gulp 		 = require('gulp');
var postcss      = require('postcss');
var gulp_postcss = require('gulp-postcss');
var min          = require('gulp-minify-css');
var cssimport    = require('postcss-import');
var autoprefixer = require('autoprefixer');
var nested       = require('postcss-nested');
var rename       = require('gulp-rename');
var mixin        = require('postcss-mixins');


gulp.task('postcss', function(){
	var processors = [
		cssimport,                       // css导入
		autoprefixer,                   // css自动加前缀
		mixin,                             // css混合函数
		nested                           // 嵌套  
	];
	return gulp.src('./css/main.css')
			.pipe(gulp_postcss(processors))
			.on('error', errorHandler)
			.pipe(rename({suffix: ".min"}))
			.pipe(gulp.dest('./css'));
});

gulp.task('watch', function(){
  gulp.watch('./css/*.css', ['postcss']);
});

gulp.task('default', ['postcss', 'watch']);
gulp.task('dev', ['postcss', 'watch']);
```

```CSS
@define-mixin border-1px $color{
        position: relative;
        &::after{
            display: block;
            content: '';
            position: absolute;
            width: 100%;
            left: 0;
            bottom: 0;
            border-top: 1px solid $color;
        }
}
/* 使用方法 */
.border-1px {
    @mixin border-1px rgba(7, 17, 27, .4);
}

/* 编译之后 */

.border-1px {
    position: relative;
}
.border-1px::after{
        display: block;
        content: '';
        position: absolute;
        width: 100%;
        left: 0;
        bottom: 0;
        border-top: 1px solid $color;    
}

@define-mixin bg-img $url{
    background-image: url(../img/2x/$url@2x.png);
    @media(-webkit-min-device-pixel-ration: 3), (min-device-pixel-ration: 3){
        background-image: url(../img/3x/$bgname@3x.png);
    }
}
```
